
services:

  app:
    build: .
    container_name: app_caderno
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - rede_sistema

  db:
    image: mariadb:10.4
    container_name: db_caderno
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - rede_sistema

networks:
  rede_sistema:
    driver: bridge